const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const tables={};let uid=0;const props={};
class Sheet{constructor(){this.r=[]}appendRow(r){this.r.push(r.map(String))}getDataRange(){return{getDisplayValues:()=>this.r.map(r=>r.map(String))}}getLastRow(){return this.r.length}getMaxRows(){return 1000}setFrozenRows(){}getRange(row,col,n,m){const api={setValues:v=>{v.forEach((r,i)=>{this.r[row-1+i]??=[];r.forEach((x,j)=>this.r[row-1+i][col-1+j]=String(x))});return api},setFontWeight:()=>api,setBackground:()=>api,setNumberFormat:()=>api};return api}deleteRow(n){this.r.splice(n-1,1)}}
const ss={insertSheet:n=>tables[n]=new Sheet(),getSheetByName:n=>tables[n],getUrl:()=>'',getId:()=> 'test'};
const context=vm.createContext({console:{log(){}},SpreadsheetApp:{create:()=>ss,openById:()=>ss,flush(){}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v})},Utilities:{getUuid:()=>String(++uid).padStart(36,'0'),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>Array.from(crypto.createHash('sha256').update(s).digest())},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock(){},releaseLock(){}})}});
vm.runInContext(fs.readFileSync(__dirname+'/../Code.gs','utf8'),context);
const c=context;c.setup_();const key='a'.repeat(72),other='b'.repeat(72);
tables.Members.appendRow(['me','Alice',c.hash_(key),'yes']);tables.Members.appendRow(['other','Bob',c.hash_(other),'yes']);
assert.throws(()=>c.getData('invalid'));
let d=c.saveData(key,'live',{title:'ライブ',date:'2026-10-01',venue:'会場'});const liveId=d.lives[0].id;
c.saveData(key,'attendance',{liveId,status:'参戦'});
d=c.saveData(key,'addTickets',{liveId,numbers:['A12','A35','A86'],status:'余り'});assert.equal(d.tickets.length,3);
assert.throws(()=>c.saveData(other,'addTickets',{liveId,numbers:['a12'],status:'余り'}));assert.equal(c.getData(key).tickets.length,3);
const t=d.tickets[0];assert.throws(()=>c.saveData(other,'ticket',{...t,status:'捌けた'}));
d=c.saveData(key,'ticket',{...t,status:'捌けた',recipient:'友人'});assert.equal(d.tickets[0].status,'捌けた');assert.throws(()=>c.saveData(key,'ticket',{...t,status:'余り'}));
c.saveData(key,'addTickets',{liveId,numbers:['',''],status:'未発券'});assert.equal(c.getData(key).tickets.length,5);
assert.throws(()=>c.saveData(key,'addTickets',{liveId,numbers:[''],status:'余り'}));
const pending=c.getData(key).tickets.find(t=>t.status==='未発券');c.saveData(key,'ticket',{...pending,number:'A99',status:'自分用'});
assert.throws(()=>c.saveData(other,'live',{...d.lives[0],title:'変更'}));
c.saveData(key,'deleteTicket',{...d.tickets[0]});assert.equal(c.getData(key).tickets.length,4);
// Upgrade an old sheet, preserving data and adding only the two new columns.
tables.Lives.r=tables.Lives.r.map(r=>r.slice(0,8));
const legacy=JSON.stringify(tables.Lives.r[1]);c.migrateLives_();c.migrateLives_();
assert.equal(JSON.stringify(tables.Lives.r[1]),legacy);
assert.equal(tables.Lives.r[0][8],'lotteryDeadline');
let live=c.getData(key).lives[0];assert.equal(live.requiredThrows,'');
live=c.saveData(key,'live',{...live,lotteryDeadline:'2026-09-25',requiredThrows:'30'}).lives[0];
assert.equal(live.lotteryDeadline,'2026-09-25');assert.equal(live.requiredThrows,'30');
for(const bad of ['-1','1.5','NaN','Infinity']) assert.throws(()=>c.saveData(key,'live',{...live,requiredThrows:bad}));
assert.throws(()=>c.saveData(key,'live',{...live,lotteryDeadline:'2026-02-30'}));
live=c.saveData(key,'live',{...live,requiredThrows:'0'}).lives[0];assert.equal(live.requiredThrows,'0');
live=c.saveData(key,'live',{...live,lotteryDeadline:'',requiredThrows:''}).lives[0];
assert.equal(live.lotteryDeadline,'');assert.equal(live.requiredThrows,'');
console.log('PASS: deadline and throw target save, validation, clearing, zero, legacy migration');
assert.equal(tables.Lives.r[0][10],'purchaseUrl');
live=c.saveData(key,'live',{...live,purchaseUrl:'https://example.com/tickets?id=12&event=3'}).lives[0];
assert.equal(live.purchaseUrl,'https://example.com/tickets?id=12&event=3');
for(const purchaseUrl of ['javascript:alert(1)','https://','data:text/html,test']) assert.throws(()=>c.saveData(key,'live',{...live,purchaseUrl}));
live=c.saveData(key,'live',{...live,purchaseUrl:''}).lives[0];assert.equal(live.purchaseUrl,'');
console.log('PASS: purchase URL persistence, validation, clearing, migration');
tables.Members.r[1][3]='no';assert.throws(()=>c.getData(key));
console.log('PASS: authentication, ownership, attendance, batch creation, duplicate rejection, transfer status, stale edits, unissued tickets, deletion, revocation');
