const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const tables={};let uid=0;const props={};
class Sheet{constructor(){this.r=[]}appendRow(r){this.r.push(r.map(String))}getDataRange(){return{getDisplayValues:()=>this.r.map(r=>r.map(String))}}getLastRow(){return this.r.length}getMaxRows(){return 1000}setFrozenRows(){}getRange(row,col,n,m){const api={setValues:v=>{v.forEach((r,i)=>{this.r[row-1+i]??=[];r.forEach((x,j)=>this.r[row-1+i][col-1+j]=String(x))});return api},setFontWeight:()=>api,setBackground:()=>api,setNumberFormat:()=>api};return api}deleteRow(n){this.r.splice(n-1,1)}}
const ss={insertSheet:n=>tables[n]=new Sheet(),getSheetByName:n=>tables[n],getUrl:()=>'',getId:()=> 'test'};
const context=vm.createContext({console:{log(){}},SpreadsheetApp:{create:()=>ss,openById:()=>ss,flush(){}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v})},Utilities:{getUuid:()=>String(++uid).padStart(36,'0'),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>Array.from(crypto.createHash('sha256').update(s).digest())},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock(){},releaseLock(){}})}});
vm.runInContext(fs.readFileSync(__dirname+'/../Code.gs','utf8'),context);
const c=context;c.setup_();c.setup_(); // Idempotent, safe for repeated first loads.
assert.equal(c.getMembers().length,0);
const alice=c.registerMember('Alice'),bob=c.registerMember('Bob');
const key=alice.id,other=bob.id;
assert.equal(c.getMembers().length,2);
assert.equal(Object.keys(c.getMembers()[0]).sort().join(','),'id,name');
assert.throws(()=>c.registerMember(' alice '));
assert.throws(()=>c.registerMember('Ａｌｉｃｅ'));
assert.throws(()=>c.registerMember('   '));
assert.throws(()=>c.registerMember('a'.repeat(41)));
assert.equal(c.getData(other).me.name,'Bob'); // Name selection is deliberately not authentication.
assert.throws(()=>c.getData('invalid'));
let d=c.saveData(key,'live',{title:'ライブ',date:'2026-10-01',venue:'会場'});const liveId=d.lives[0].id;
c.saveData(key,'attendance',{liveId,status:'参戦'});
d=c.saveData(key,'addTickets',{liveId,numbers:['A12','A35','A86'],status:'余り'});assert.equal(d.tickets.length,3);
assert.throws(()=>c.saveData(other,'addTickets',{liveId,numbers:['a12'],status:'余り'}));assert.equal(c.getData(key).tickets.length,3);
const t=d.tickets[0];assert.throws(()=>c.saveData(other,'ticket',{...t,status:'捌けた'}));
d=c.saveData(key,'ticket',{...t,status:'捌けた',recipient:'友人'});assert.equal(d.tickets[0].status,'捌けた');assert.throws(()=>c.saveData(key,'ticket',{...t,status:'余り'}));
c.saveData(key,'addTickets',{liveId,numbers:['',''],status:'未発券'});assert.equal(c.getData(key).tickets.length,5);
assert.throws(()=>c.saveData(key,'addTickets',{liveId,numbers:[''],status:'余り'}));
const pending=c.getData(key).tickets.find(t=>t.status==='未発券');c.saveData(key,'ticket',{...pending,number:'A99',status:'自分用'});
assert.throws(()=>c.saveData(other,'live',{...d.lives[0],title:'変更'}));
c.saveData(key,'deleteTicket',{...d.tickets[0]});assert.equal(c.getData(key).tickets.length,4);
// Upgrade an old sheet, preserving data and adding only the two new columns.
tables.Lives.r=tables.Lives.r.map(r=>r.slice(0,8));
const legacy=JSON.stringify(tables.Lives.r[1]);c.migrateLives_();c.migrateLives_();
assert.equal(JSON.stringify(tables.Lives.r[1]),legacy);
assert.equal(tables.Lives.r[0][8],'抽選締切');
let live=c.getData(key).lives[0];assert.equal(live.requiredThrows,'');
live=c.saveData(key,'live',{...live,lotteryDeadline:'2026-09-25',requiredThrows:'30'}).lives[0];
assert.equal(live.lotteryDeadline,'2026-09-25');assert.equal(live.requiredThrows,'30');
for(const bad of ['-1','1.5','NaN','Infinity']) assert.throws(()=>c.saveData(key,'live',{...live,requiredThrows:bad}));
assert.throws(()=>c.saveData(key,'live',{...live,lotteryDeadline:'2026-02-30'}));
live=c.saveData(key,'live',{...live,requiredThrows:'0'}).lives[0];assert.equal(live.requiredThrows,'0');
live=c.saveData(key,'live',{...live,lotteryDeadline:'',requiredThrows:''}).lives[0];
assert.equal(live.lotteryDeadline,'');assert.equal(live.requiredThrows,'');
console.log('PASS: deadline and throw target save, validation, clearing, zero, legacy migration');
assert.equal(tables.Lives.r[0][10],'チケット購入URL');
live=c.saveData(key,'live',{...live,purchaseUrl:'https://example.com/tickets?id=12&event=3'}).lives[0];
assert.equal(live.purchaseUrl,'https://example.com/tickets?id=12&event=3');
for(const purchaseUrl of ['javascript:alert(1)','https://','data:text/html,test']) assert.throws(()=>c.saveData(key,'live',{...live,purchaseUrl}));
live=c.saveData(key,'live',{...live,purchaseUrl:''}).lives[0];assert.equal(live.purchaseUrl,'');
console.log('PASS: purchase URL persistence, validation, clearing, migration');
live=c.saveData(key,'live',{...live,groups:['グループA','グループB','グループA']}).lives[0];
assert.equal(live.groups.join(','),'グループA,グループB');
assert.equal(c.getData(other).groups.join(','),'グループA,グループB');
assert.throws(()=>c.saveData(key,'live',{...live,groups:Array(21).fill('グループ')}));
assert.throws(()=>c.saveData(key,'live',{...live,groups:['']}));
assert.throws(()=>c.saveData(key,'live',{...live,groups:['bad,name']}));
live=c.saveData(key,'live',{...live,groups:['グループB']}).lives[0];
assert.equal(live.groups.join(','),'グループB');
live=c.saveData(key,'live',{...live,groups:[]}).lives[0];assert.equal(live.groups.length,0);
console.log('PASS: reusable group tags, deduplication, validation, deselection and clearing');
tables.Members.r[1][3]='no';assert.throws(()=>c.getData(key));
console.log('PASS: name registration and selection, selected-member ownership, attendance, batch creation, duplicate rejection, transfer status, stale edits, unissued tickets, deletion, revocation');

// Spreadsheet bulk entry and header migration preserve IDs and related records.
const oldTickets=JSON.stringify(tables.Tickets.r);
const existingId=tables.Lives.r[1][0];
tables.Lives.appendRow(['','まとめ登録','2026-11-01','会場','','',other,'','','5']);
tables.Lives.appendRow([]);
tables.Members.appendRow(['','新しいメンバー']);
props.SCHEMA_VERSION='name-selection-v2';
context._testTables=tables;
vm.runInContext("Object.keys(TABLES).forEach(n=>{_testTables[n].r[0]=Array.from(TABLES[n]);});",context);
c.ensureReady_();
assert.equal(tables.Lives.r[0][1],'イベント名');
assert.equal(tables.Members.r[0][1],'名前');
assert.equal(tables.Lives.r[1][0],existingId);
assert.equal(JSON.stringify(tables.Tickets.r),oldTickets);
const imported=c.getData(other).lives.find(l=>l.title==='まとめ登録');
assert.ok(imported.id);assert.equal(imported.version,'1');
assert.ok(c.getMembers().find(m=>m.name==='新しいメンバー').id);
assert.equal(tables.Lives.r[3][0],undefined);
c.ensureReady_();assert.equal(c.getData(other).lives.find(l=>l.title==='まとめ登録').id,imported.id);
c.saveData(other,'live',{...imported,title:'まとめ登録を編集'});
tables.Lives.appendRow([existingId,'重複','2026-11-02']);
assert.throws(()=>c.ensureReady_(),/IDが重複/);
console.log('PASS: Japanese migration preserves data, bulk IDs persist, blank rows skipped, duplicates rejected, imported event editable');
