const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const script=fs.readFileSync(__dirname+'/../docs/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const c=vm.createContext({sessionStorage:{removeItem(){}},localStorage:{getItem:()=>''}});vm.runInContext(script.slice(0,script.indexOf('function showSetup()')),c);
vm.runInContext("data={me:{id:'me'},members:[{id:'me'},{id:'other'}]};",c);
assert.equal(c.japanDay(new Date('2026-09-19T14:59:59Z')),'2026-09-19');
assert.equal(c.japanDay(new Date('2026-09-19T15:00:00Z')),'2026-09-20');
assert.equal(c.nextDay('2026-12-31'),'2027-01-01');
const event=(id,date,lotteryDeadline)=>({id,title:id,date,lotteryDeadline,venue:'会場',requiredThrows:'5',purchaseUrl:'https://example.com/tickets',sheetUrl:'https://docs.google.com/spreadsheets/d/example/edit'});
const events=[event('future','2026-10-03','2026-09-25'),event('tomorrow','2026-10-02','2026-09-20'),event('today-cutoff','2026-10-04','2026-09-19'),event('past','2026-09-01','2026-08-20'),event('today-show','2026-09-19','2026-09-19'),event('earlier','2026-10-01','2026-09-25')];
assert.equal(c.sortedEvents(events,'2026-09-19').map(e=>e.id).join(','),'today-show,today-cutoff,tomorrow,past,earlier,future');
const l=events[2],tickets=['余り','余り','取引中','自分用','捌けた','未発券'].map(status=>({liveId:l.id,status}));tickets.push({liveId:'another',status:'余り'});
for(const day of ['2026-09-18','2026-09-19']){const html=c.eventTile(l,tickets,day);assert.ok(html.includes('チケットURL'));assert.ok(html.includes('投げ数'));assert.ok(!html.includes('全体あまり数'));assert.ok(!html.includes('関連スプシURL'))}
const after=c.eventTile(l,tickets,'2026-09-20');assert.ok(after.includes('全体あまり数</dt><dd>2枚'));assert.ok(after.includes('関連スプシURL'));assert.ok(!after.includes('チケットURL'));assert.ok(!after.includes('投げ数'));
assert.ok(c.eventTile({...l,lotteryDeadline:''},[],'2026-09-20').includes('抽選締切</dt><dd>未設定'));
assert.ok(!c.safeLink('javascript:alert(1)','チケットURL').includes('href='));
assert.ok(c.eventTile({...l,title:'<script>bad</script>'},[],'2026-09-19').includes('&lt;script&gt;'));
assert.ok(c.eventTile({...l,groups:['グループA','<script>']},[],'2026-09-19').includes('グループA'));
assert.ok(c.eventTile({...l,groups:['<script>']},[],'2026-09-19').includes('&lt;script&gt;'));
console.log('PASS: priority ordering, Japan midnight, year rollover, cutoff day/next day tile content, remaining count, unset cutoff, safe links and escaping');

assert.ok(c.eventTile({...l,owner:'me'},[],'2026-09-19').includes('data-edit-live='));
assert.ok(c.eventTile({...l,owner:'bad-import-id'},[],'2026-09-19').includes('data-edit-live='));
assert.ok(!c.eventTile({...l,owner:'other'},[],'2026-09-19').includes('data-edit-live='));
assert.ok(!script.includes('setInterval('));
assert.ok(!script.includes('60秒ごと'));
console.log('PASS: edit buttons for owned/imported events, other-owner guard, no periodic refresh');

vm.runInContext("data={me:{id:'me'},members:[{id:'me',name:'本人'},{id:'other',name:'<友人>'},{id:'pending',name:'未回答の人'}],attendance:[{liveId:'event',memberId:'me',status:'参戦'},{liveId:'event',memberId:'other',status:'不参加'}]};",c);
const dropdown=c.attendanceDropdown({id:'event'});
assert.ok(dropdown.includes('1人参戦'));assert.ok(dropdown.includes('不参加'));assert.ok(dropdown.includes('未回答'));assert.ok(dropdown.includes('&lt;友人&gt;'));
const otherDropdown=c.attendanceDropdown({id:'different'});assert.ok(otherDropdown.includes('0人参戦'));
let renders=0,requests=0,historyBack=0;
c.window={scrollY:240,scrollTo(){}};c.location={pathname:'/app',search:''};
c.document={getElementById:()=>({open:false})};
c.history={state:{ticketView:'home'},pushState(state){this.state=state},replaceState(state){this.state=state},back(){historyBack++;this.state={ticketView:'home'};c.handleHistory()}};
c.render=()=>renders++;c.rpc=()=>{requests++;throw Error('unexpected request')};
c.openEvent('event');assert.equal(c.history.state.id,'event');c.returnHome();
assert.equal(historyBack,1);assert.equal(renders,2);assert.equal(requests,0);
const storage={};c.sessionStorage={setItem:(k,v)=>storage[k]=v,getItem:k=>storage[k]||null};c.window.LIVE_POCKET_CONFIG={gasUrl:'endpoint'};
vm.runInContext("memberId='me';data={me:{id:'me'},lives:[],members:[],tickets:[],attendance:[]};",c);
c.cacheSnapshot();assert.equal(c.restoreSnapshot(),true);
vm.runInContext("memberId='other';",c);assert.equal(c.restoreSnapshot(),false);
vm.runInContext("memberId='me';",c);c.window.LIVE_POCKET_CONFIG.gasUrl='different';assert.equal(c.restoreSnapshot(),false);
console.log('PASS: attendance per event including unanswered/escaping, browser back without RPC, cache member/endpoint isolation');
