const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
let handler,frame,seq=0,timer=0;const timers=new Map(),sent=[];
const peer={postMessage:(message,origin)=>sent.push({message,origin})};
const context={URL,Set,Map,Promise,Error,crypto:{randomUUID:()=>`00000000-0000-0000-0000-${String(++seq).padStart(12,'0')}`},setTimeout:(cb)=>{timers.set(++timer,cb);return timer},clearTimeout:id=>timers.delete(id),window:{LIVE_POCKET_CONFIG:{gasUrl:'https://script.google.com/macros/s/example/exec'},addEventListener:(_,fn)=>handler=fn,removeEventListener(){}},document:{createElement:()=>({setAttribute(){},remove(){}}),body:{appendChild:x=>frame=x}}};
vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../docs/transport.js','utf8'),context);
const result=context.window.LivePocketTransport.call('getMembers');
const channel=new URL(frame.src).searchParams.get('channel');
handler({origin:'https://evil.example',source:peer,data:{type:'live-pocket-ready',channel}});
assert.equal(sent.length,0);
handler({origin:'https://n-test-script.googleusercontent.com',source:peer,data:{type:'live-pocket-ready',channel}});
await new Promise(setImmediate);assert.equal(sent.length,1);
const request=sent[0].message;let done=false;result.then(()=>done=true);
handler({origin:sent[0].origin,source:{},data:{type:'live-pocket-result',channel,id:request.id,ok:true,value:'bad'}});
await new Promise(setImmediate);assert.equal(done,false);
handler({origin:sent[0].origin,source:peer,data:{type:'live-pocket-result',channel,id:request.id,ok:true,value:[{id:'1',name:'test'}]}});
assert.equal((await result)[0].name,'test');
const mutation=context.window.LivePocketTransport.call('saveData','1','attendance',{});await new Promise(setImmediate);
const timeout=[...timers.values()][0];timeout();await assert.rejects(mutation,/登録済みの可能性/);assert.equal(sent.length,2);
await assert.rejects(context.window.LivePocketTransport.call('setup_'),/未対応/);
let bridgeListener;const calls=[],replies=[];const top={postMessage:(m,o)=>replies.push({m,o})};
const runner={withSuccessHandler(fn){this.success=fn;return this},withFailureHandler(){return this},getMembers(){calls.push('getMembers');this.success([{id:'1',name:'test'}])}};
const bridge={window:{top,addEventListener:(_,fn)=>bridgeListener=fn},google:{script:{run:runner}},Set,JSON};vm.createContext(bridge);
let code=fs.readFileSync(__dirname+'/../Bridge.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace('<?!= JSON.stringify(channel) ?>',JSON.stringify(channel)).replace('<?!= JSON.stringify(parentOrigin) ?>',JSON.stringify('https://m0ch4771.github.io'));
vm.runInContext(code,bridge);
const message={type:'live-pocket-call',channel,id:request.id,method:'getMembers',args:[]};
bridgeListener({origin:'https://evil.example',source:top,data:message});assert.equal(calls.length,0);
bridgeListener({origin:'https://m0ch4771.github.io',source:top,data:message});assert.equal(calls.length,1);
bridgeListener({origin:'https://m0ch4771.github.io',source:top,data:message});assert.equal(calls.length,1);
assert.equal(replies[1].m.ok,true);assert.equal(replies[1].o,'https://m0ch4771.github.io');
console.log('PASS: iframe handshake, origin/source checks, RPC response, mutation timeout without retry, method allowlist, bridge reply and replay prevention');
})().catch(e=>{console.error(e);process.exit(1)});
